/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.ConexionSingleton;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Productor;

/**
 *
 * @author macbook
 */
public class VentanaCrudProductor extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCrudProductor
     */
    public VentanaCrudProductor() {
        initComponents();
        recuperaProductores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSelect = new javax.swing.JLabel();
        jComboBoxDatosProductor = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidoP = new javax.swing.JLabel();
        jLabelApellidoM = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidoP = new javax.swing.JTextField();
        jTextFieldApellidoM = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jButtonEmpezarEditar = new javax.swing.JButton();
        jLabelCargo = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldCargo = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSelect.setText("Selecciona una productor: ");

        jComboBoxDatosProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDatosProductorActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre");

        jLabelApellidoP.setText("Apellido paterno");

        jLabelApellidoM.setText("Apellido materno");

        jLabelDireccion.setText("Dirección");

        jLabelTelefono.setText("Teléfono");

        jTextFieldNombre.setEnabled(false);

        jTextFieldApellidoP.setEnabled(false);

        jTextFieldApellidoM.setEnabled(false);

        jTextFieldDireccion.setEnabled(false);

        jTextFieldTelefono.setEnabled(false);

        jButtonAgregar.setText("Registrar nuevo productor");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar datos productor");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar productor");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido paterno", "Apellido materno", "Dirección", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDatos);

        jButtonEmpezarEditar.setText("Empezar a editar");
        jButtonEmpezarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpezarEditarActionPerformed(evt);
            }
        });

        jLabelCargo.setText("Cargo");

        jLabelPassword.setText("Password");

        jTextFieldCargo.setEnabled(false);

        jPasswordField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBorrar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNombre)
                                            .addComponent(jLabelApellidoP)
                                            .addComponent(jLabelApellidoM)
                                            .addComponent(jLabelPassword))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldApellidoP)
                                                    .addComponent(jTextFieldApellidoM)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDireccion)
                                            .addComponent(jLabelTelefono)
                                            .addComponent(jLabelCargo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSelect)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxDatosProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTelefono)
                                    .addComponent(jButtonEmpezarEditar)
                                    .addComponent(jTextFieldCargo))))
                        .addGap(5, 5, 5))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSelect)
                            .addComponent(jComboBoxDatosProductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEmpezarEditar))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDireccion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoP)
                            .addComponent(jLabelTelefono)
                            .addComponent(jTextFieldApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellidoM)
                            .addComponent(jTextFieldApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCargo)))
                    .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonCancelar))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEmpezarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpezarEditarActionPerformed
            // TODO add your handling code here:
            jTextFieldNombre.setEnabled(true);
            jTextFieldApellidoP.setEnabled(true);
            jTextFieldApellidoM.setEnabled(true);
            jTextFieldDireccion.setEnabled(true);
            jTextFieldTelefono.setEnabled(true);
            jTextFieldCargo.setEnabled(true);
            jPasswordField.setEnabled(true);
            //jTextFieldTelefono.setEnabled(true);
            
           
    }//GEN-LAST:event_jButtonEmpezarEditarActionPerformed

    private void jComboBoxDatosProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDatosProductorActionPerformed
        // TODO add your handling code here:
        String nombre = jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getNombre();
        String apellidoM = jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getApellidoM();
        String apellidoP = jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getApellidoP();
        String telefono = jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getTelefono();
        String cargo = jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getCargo();
        String direccion = jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getDireccion();
        String password =jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getPassword();
        //System.out.println("nombre seleccionado "+id);

        jTextFieldNombre.setText(nombre);
        jTextFieldApellidoP.setText(apellidoP);
        jTextFieldApellidoM.setText(apellidoM);
        jTextFieldDireccion.setText(direccion);
        jTextFieldTelefono.setText(telefono);
        jTextFieldCargo.setText(cargo);
        jPasswordField.setText(password);
    }//GEN-LAST:event_jComboBoxDatosProductorActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        //int id = jComboBoxListaNombres.getItemAt(jComboBoxListaNombres.getSelectedIndex()).getId();
        
        String nombreC = jTextFieldNombre.getText();
        String apellidoMC = jTextFieldApellidoM.getText();
        String apellidoPC = jTextFieldApellidoP.getText();
        String direccionC = jTextFieldDireccion.getText();
        String telefonoC = jTextFieldTelefono.getText();
        String cargoC = jTextFieldCargo.getText();
        String passwordC = new String(jPasswordField.getPassword());
        int ContID=1;
        Connection con = ConexionSingleton.getInstance();
        ContID+=1;

        try {
            
            //(2) Crear un objeto statement
            Statement st = (Statement) con.createStatement();

            String consulta = "INSERT INTO `Productor` (`ID`, `Nombre`, `ApellidoP`, `ApellidoM`, `Direccion`, `Telefono`, `Cargo`, `Password`) VALUES ('"+ContID+"', '"+nombreC+"', '"+apellidoMC+"', '"+apellidoPC+"', '"+direccionC+"', '"+telefonoC+"', '"+cargoC+"', '"+passwordC+"')";
            
            /*INSERT INTO `Productor` (`ID`, `Nombre`, `ApellidoP`, `ApellidoM`, `Direccion`, `Telefono`, `Cargo`, `Password`) VALUES ('3', 'julian', 'Contreras ', 'Lezama', 'coatepec', '2134564', 'Cocinero de tamales', '123');*/

            // `idCliente`='"+id;
            
            if (st.executeUpdate(consulta) == 1) {
                
                JOptionPane.showMessageDialog(null, "Registro agregado");
                System.out.println(consulta);
                //ContID++;
                limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Registro no agregado");
                System.out.println(consulta);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        int idProductor = jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getID();

        String nombreC = jTextFieldNombre.getText();
        String apellidoMC = jTextFieldApellidoM.getText();
        String apellidoPC = jTextFieldApellidoP.getText();
        String direccionC = jTextFieldDireccion.getText();
        String telefonoC = jTextFieldTelefono.getText();
        String cargoC = jTextFieldCargo.getText();
        String passwordC = new String(jPasswordField.getPassword());
        
        //String passwordCliente = jPasswordFieldContraseña.getText();
        Connection con = ConexionSingleton.getInstance();

        try {
            //(2) Crear un objeto statement
            Statement st = (Statement) con.createStatement();

            String consulta = "UPDATE `Productor` SET `Nombre`='" + nombreC;
            consulta += "' ,`ApellidoP`='" + apellidoPC;
            consulta += "' ,`ApellidoM`='" + apellidoMC;
            consulta += "' ,`Direccion`='" + direccionC;
            consulta += "' ,`Telefono`='" + telefonoC;
            consulta += "' ,`Cargo`='" + cargoC;
            consulta += "',`Password`='" + passwordC;
            consulta += "' WHERE (`ID` = '" + idProductor;
            consulta += "')";

            // `idCliente`='"+id;
            if (st.executeUpdate(consulta) == 1) {
                JOptionPane.showMessageDialog(null, "Registro actualizado");
                System.out.println(consulta);
                
                limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Registro no actualizado");
                System.out.println(consulta);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        int idSeleccionado = jComboBoxDatosProductor.getItemAt(jComboBoxDatosProductor.getSelectedIndex()).getID();
        Connection con = ConexionSingleton.getInstance();

        try {
            //(2) Crear un objeto statement
            Statement st = (Statement) con.createStatement();
            
            String consulta="DELETE FROM `Productor` WHERE (`ID` = '"+idSeleccionado;
            consulta+="')";
            
           // `idCliente`='"+id;

            if (st.executeUpdate(consulta) == 1) {
                JOptionPane.showMessageDialog(null, "Registro eliminado");
                System.out.println(consulta);
                 limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado");
                System.out.println(consulta);
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    public void limpiar() {
        jTextFieldNombre.setText("");
        jTextFieldApellidoP.setText("");
        jTextFieldApellidoM.setText("");
        jTextFieldDireccion.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldCargo.setText("");
        jPasswordField.setText("");

    }

    public void recuperaProductores() {
        Productor productor = new Productor();
        ArrayList<Productor> nombreClientes = productor.getProductor();
        jComboBoxDatosProductor.removeAllItems();
        //recorrer la lista
        for (int i = 0; i < nombreClientes.size(); i++) {
            //jComboBoxListaNombres.addItem(nombreClientes.get(i).getNombre());
            jComboBoxDatosProductor.addItem(new Productor(nombreClientes.get(i).getID(), nombreClientes.get(i).getNombre(), nombreClientes.get(i).getApellidoP(),nombreClientes.get(i).getApellidoM(),nombreClientes.get(i).getDireccion(),nombreClientes.get(i).getTelefono(),nombreClientes.get(i).getCargo(), nombreClientes.get(i).getPassword()));
           
        }

    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrudProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrudProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrudProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrudProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrudProductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEmpezarEditar;
    private javax.swing.JComboBox<Productor> jComboBoxDatosProductor;
    private javax.swing.JLabel jLabelApellidoM;
    private javax.swing.JLabel jLabelApellidoP;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSelect;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jTextFieldApellidoM;
    private javax.swing.JTextField jTextFieldApellidoP;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
